title                   = 'Explore my world'
baseURL                 = 'https://surajcm.github.io/blog'
theme                   = "ananke"
languageCode            = 'en-us'
resourceDir             = "../resources"

DefaultContentLanguage  = "en"
SectionPagesMenu        = "main"
Paginate                = 5
googleAnalytics         = ""
enableRobotsTXT         = true

[menu]

  [[menu.main]]
    name              = "Home"
    identifier        = "home"
    url               = ""
    pre               = "<i class='fa fa-home'></i>"
    weight            = 1

  [[menu.main]]
    name              = "About"
    identifier        = "about"
    url               = "https://surajcm.github.io/#about"
    pre               = "<i class='far fa-id-card'></i>"
    weight            = 2

  [[menu.main]]
    name              = "Blog"
    identifier        = "blog"
    url               = "https://surajcm.github.io/blog"
    pre               = "<i class='far fa-newspaper'></i>"
    weight            = 3

  [[menu.main]]
    name              = "Categories"
    identifier        = "categories"
    url               = "categories"
    pre               = "<i class='fas fa-sitemap'></i>"
    weight            = 5

  [[menu.main]]
    name              = "Contact"
    identifier        = "contact"
    url               = "https://surajcm.github.io/#contact"
    pre               = "<i class='far fa-envelope'></i>"
    weight            = 6

    
[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  #background_color_class = "bg-black"
  #body_classes = "athelas bg-moon-gray"
  #custom_css = ["custom.css"]
  custom_css = ["search.css"]
  #background_color_class = "bg-dark-gray"
  #body_classes = "helvetica bg-washed-blue"
  body_classes = "avenir jib-blue"
  cover_dimming_class = "bg-transparent"

